name: SauceDemo - Cypress BDD + Allure

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]
  workflow_dispatch:
    inputs:
      tags:
        description: "Cucumber tag expression"
        required: false
        default: "@regression"

permissions:
  contents: read

jobs:
  cypress:
    name: E2E - Cypress + Cucumber
    runs-on: ubuntu-24.04
    timeout-minutes: 20

    env:
      CYPRESS_BASE_URL: https://www.saucedemo.com
      CYPRESS_TAGS: ${{ github.event.inputs.tags || '@regression' }}

    defaults:
      run:
        working-directory: saucedemo-cypress-cucumber

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          #cache: npm
          #cache-dependency-path: saucedemo-cypress-cucumber/package-lock.json

      - name: Install dependencies
        run: npm install --include=dev

      - name: Lint
        run: npm run lint

      - name: Format files
        run: npx prettier --write . --config .prettierc.js  

      - name: Format check
        run: npx prettier --check . --config .prettierc.js

      - name: Run Cypress
        id: cypress
        continue-on-error: true
        run: npm test

      - name: Generate Allure report
        if: always()
        run: |
          mkdir -p allure-results
          npm exec -- allure generate allure-results --clean -o allure-report

      - name: Upload Allure raw results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: allure-results
          path: saucedemo-cypress-cucumber/allure-results
          if-no-files-found: warn
          retention-days: 14

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: screenshots
          path: saucedemo-cypress-cucumber/cypress/screenshots
          if-no-files-found: ignore
          retention-days: 14

      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: videos
          path: saucedemo-cypress-cucumber/cypress/videos
          if-no-files-found: ignore
          retention-days: 14

      - name: Upload Allure report for deployment
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: allure-report
          path: saucedemo-cypress-cucumber/allure-report
          if-no-files-found: warn
          retention-days: 14

      - name: Fail job if Cypress failed
        if: steps.cypress.outcome == 'failure'
        run: exit 1